// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ7JzfuOE7FGeE96FqmaAGnUizMf2Of8E',
    appId: '1:683356179012:web:de99d1214161656c7c0a11',
    messagingSenderId: '683356179012',
    projectId: 'fit-streaks-0133',
    authDomain: 'fit-streaks-0133.firebaseapp.com',
    storageBucket: 'fit-streaks-0133.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2kG3ZGdTYQX4HI6p6kG7dbUEeMeRo0kY',
    appId: '1:683356179012:android:d60aae8c794eb31a7c0a11',
    messagingSenderId: '683356179012',
    projectId: 'fit-streaks-0133',
    storageBucket: 'fit-streaks-0133.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoO-2wYR4E4haLQmtzt5ehoBcGXT7gSu4',
    appId: '1:683356179012:ios:2c1c49ff5a15dd317c0a11',
    messagingSenderId: '683356179012',
    projectId: 'fit-streaks-0133',
    storageBucket: 'fit-streaks-0133.appspot.com',
    iosBundleId: 'com.example.fitstreaks',
  );
}
